# Basic Setup Variables
baseURL: "/"
languageCode: en
title: "Faded"
theme: faded
MetaDataFormat: yaml

params:
  description: "A Little Bit Lighter Than Most"
  profilePath: "img/faded.jpg"
  errorPath: "img/faded.jpg"

social:
  # site: "profile URL you want to link to"
  behance: "behance"
  btc: "btc"
  codepen: "https://codepen.io/Bern_"
  deviantart: "deviantart"
  dribbble: "dribble"
  etsy: "etsy"
  facebook: "https://www.facebook.com/bern.carney"
  flickr: "flickr"
  github: "https://github.com/BernCarney"
  gitlab: "gitlab"
  google-plus: "googleplus"
  instagram: "https://www.instagram.com/bern.carney"
  jsfiddle: jsfiddle
  lastfm: lastfm
  linkedin: "https://www.linkedin.com/in/berncarney"
  medium: medium
  pinterest: pinterest
  reddit: reddit
  skype: skype
  snapchat: snapchat
  spotify: "https://open.spotify.com/user/bernjc3"
  stack-overflow: stackoverflow
  steam: steam
  tumblr: tumblr
  twitch: twitch
  twitter: "https://twitter.com/BCarney_"
  vimeo: vimeo
  vine: vine
  wechat: wechat
  yelp: yelp
  youtube: youtube
